# Generated by Django 2.2.5 on 2019-10-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20191008_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
    ]
